# Generated by Django 5.1.15 on 2026-09-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_assistant_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, unique=True)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='LaboratoryWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('report_deadline', models.DateField()),
                ('defense_deadline', models.DateField()),
                ('report_weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('defense_weight', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
