# Generated by Django 5.1.15 on 2026-09-15 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_criterion_laboratorywork'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateField()),
                ('lab_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.laboratorywork')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'lab_work'), name='uq_report_student_lab')],
            },
        ),
    ]
