# Generated by Django 5.1.15 on 2026-09-15 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_labreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defense_date', models.DateField()),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defense', to='core.labreport')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defenses', to='core.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ReportReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='core.assistant')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.labreport')),
            ],
        ),
    ]
