# Generated by Django 5.1.15 on 2026-09-15 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_defense_reportreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='core.criterion')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_results', to='core.reportreview')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('review', 'criterion'), name='uq_review_criterion')],
            },
        ),
    ]
