# Generated by Django 5.1.15 on 2026-09-15 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_criterionresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineResult',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.student')),
                ('bonus_points', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('exam_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('auto_pass_agree', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SickLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена')], default='pending', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sick_leaves', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('present', 'Присутствовал'), ('absent', 'Отсутствовал'), ('sick', 'Болел')], max_length=10, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'lesson_date'), name='uq_attendance_student_date')],
            },
        ),
    ]
