# Generated by Django 5.1.15 on 2026-09-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_disciplinesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='submitted_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
