# Generated by Django 5.1.15 on 2026-09-16 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_labreport_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defense',
            name='defense_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defense',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.labreport'),
        ),
        migrations.AlterField(
            model_name='defense',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher'),
        ),
    ]
