# Generated by Django 5.1.15 on 2026-09-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_attendance_status_alter_attendance_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sickleave',
            name='file_url',
        ),
        migrations.AddField(
            model_name='sickleave',
            name='file',
            field=models.FileField(default='', upload_to='sick_leaves/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sickleave',
            name='status',
            field=models.CharField(choices=[('на рассмотрении', 'На рассмотрении'), ('подтверждена', 'Подтверждена'), ('отклонена', 'Отклонена')], default='на рассмотрении', max_length=20),
        ),
    ]
